"""add permission updated_at

Revision ID: 06ae98165f23
Revises: 75361dd9ab82
Create Date: 2026-09-30 10:49:13.104571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ae98165f23'
down_revision: Union[str, Sequence[str], None] = '75361dd9ab82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'permissions',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.execute(
        "UPDATE permissions SET updated_at = created_at WHERE updated_at IS NULL"
    )

    op.alter_column(
        'permissions',
        'updated_at',
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'updated_at')
    # ### end Alembic commands ###
