"""add extracted text to documents

Revision ID: 17393998ba44
Revises: eb7c4b939028
Create Date: 2026-09-22 15:57:16.154351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17393998ba44'
down_revision: Union[str, Sequence[str], None] = 'eb7c4b939028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
