"""add password hash to users

Revision ID: 44c94442d4aa
Revises: 8ef121737670
Create Date: 2026-09-21 12:39:40.652794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c94442d4aa'
down_revision: Union[str, Sequence[str], None] = '8ef121737670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("password_hash", sa.String(length=255), nullable=True),
    )

    op.execute(
        """
        UPDATE users
        SET password_hash = '$argon2id$v=19$m=65536,t=3,p=4$RsC2dyLHs1K2QpUoKEuSlA$+VICFGtVeQf67YuQ+i1AZH85HhMisUgivoXcRiYaVVQ'
        WHERE password_hash IS NULL
        """
    )

    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.String(length=255),
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
