"""add resource type to documents

Revision ID: 62c9e8a486bd
Revises: bb7357a7de87
Create Date: 2026-09-23 14:19:16.250095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c9e8a486bd'
down_revision: Union[str, Sequence[str], None] = 'bb7357a7de87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'documents',
        sa.Column(
            'resource_type',
            sa.String(length=50),
            nullable=False,
            server_default='general',
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'resource_type')
    # ### end Alembic commands ###
